name: Node.js CI
on:
  push:
    branches: [ AT ]
  pull_request:
    branches: [ AT ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{secrets.PORT}} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.TEST_BRANCH }} && git pull && exit"
      - name: cleanup
        run: rm -rf ~/.ssh