name: Node.js CI
on:
  push:
    branches: [ AT ]
  pull_request:
    branches: [ AT ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install npm dependecies
      run: npm install
    - name: Run build
      run: npm run build --if-present
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        password: ${{ secrets.PASSWORD }}
        proxy_port: ${{ secrets.PORT }}
        script: whoami