name: Node.js CI
on:
  push:
    branches: [ AT ]
  pull_request:
    branches: [ AT ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Install SSH Key
        uses: shimatrao/ssh-key-action@v2
        with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         known_hosts: 'placeholder_for_errors'
      #- name: Adding Known Hosts
       #  run: ssh-keyscan
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependecies
        run: npm install
      - name: Build
        run: npm run build
      - name: Push to DEV environment
        run: git pull