name: Node.js CI
on:
  push:
    branches: [ AT ]
  pull_request:
    branches: [ AT ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         known_hosts: 'known-placeholder'
      - name: Get Known Hosts
        run: rm -rf ~/.ssh/known_hosts
        #run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependecies
        run: npm install
      - name: Build
        run: npm run build
      - name: Push to DEV environment
        run: git pull